version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          cypress-command: npx cypress run --parallel --record
          parallelism: 2
          requires:
            - cypress/install
          store_artifacts: true
          spec: cypress/e2e/Test.cy.js
